name: Build on Tag

on:
  push:
    # fire on semver-style tags, e.g. v0.1.0, v2.3.4
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build
